# Combining DataFrames in Pandas
---

In today's project, we're going to look at nutritional information from several chain restaurants. The problem is our data is split up into several CSVs. We'll need to combine them into one dataframe, which is a very important skillset as a data scientist.

## Concatenation: Setup

1. Create two dataframes from **foods-a.csv** and ** foods-b.csv**. 
2. For each dataframe, set the index to be the `id` column.

In [42]:
import pandas as pd
foods_a=pd.read_csv('foods-a.csv')
foods_b=pd.read_csv('foods-b.csv')

## Concatenating along the column axis

It's not enough to merely combine two dataframes, we have to specify whether we want them to be combined along the row axis (**axis=0**) or column axis (**axis=1**). Since our two dataframes have the same column of data, we'll want to combine them along the row axis.

Using pandas' [concat](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html) method, combine our two food dataframes into one:

In [43]:
foods=pd.concat([foods_a,foods_b],axis=0)
foods.head()

   id                 name
0   1  A&W® Diet Root Beer
1   2  A&W® Diet Root Beer
2   3  A&W® Diet Root Beer
3   4  A&W® Diet Root Beer
4   5  A&W® Diet Root Beer

Compare the shape of your combined dataframe to the shapes of the original two dataframes.

In [44]:
nutrition=pd.read_csv('nutrition.csv')
nutrition.head()

   id  calories  carbs  fat
0   1         0    0.0    0
1   2         0    0.0    0
2   3         0    0.0    0
3   4         0    0.0    0
4   5         0    0.0    0

## Concatenating along the column axis

Now that we have our dataframe, let's add some nutritional information. 

1. Create a dataframe from **nutrition.csv**
2. Set your index to be the id column, so that our nutrition index matches our food names index

In [30]:
nutrition.head()

   id  calories  carbs  fat
0   1         0    0.0    0
1   2         0    0.0    0
2   3         0    0.0    0
3   4         0    0.0    0
4   5         0    0.0    0

In [36]:
#nutrition.set_index('id',inplace=True)
nutrition.head()

    calories  carbs  fat
id
1          0    0.0    0
2          0    0.0    0
3          0    0.0    0
4          0    0.0    0
5          0    0.0    0

In [34]:
#foods.set_index('id', inplace=True)
foods.head()

                   name
id
1   A&W® Diet Root Beer
2   A&W® Diet Root Beer
3   A&W® Diet Root Beer
4   A&W® Diet Root Beer
5   A&W® Diet Root Beer

In [16]:
pd.concat([foods,nutrition],axis=1)

                                      name  calories  carbs  fat
id
1                      A&W® Diet Root Beer         0    0.0    0
2                      A&W® Diet Root Beer         0    0.0    0
3                      A&W® Diet Root Beer         0    0.0    0
4                      A&W® Diet Root Beer         0    0.0    0
5                      A&W® Diet Root Beer         0    0.0    0
6                      A&W® Diet Root Beer         0    0.0    0
7        A&W® Diet Root Beer Float (large)       350   60.0   10
8       A&W® Diet Root Beer Float (medium)       170   30.0    5
9        A&W® Diet Root Beer Float (small)       170   30.0    5
10      A&W® Diet Root Beer Freeze (large)       600   92.0   18
11     A&W® Diet Root Beer Freeze (medium)       340   53.0   10
12      A&W® Diet Root Beer Freeze (small)       260   39.0    8
13                          A&W® Root Beer       160   43.0    0
14                          A&W® Root Beer       220   58.0    0
15                          A&W® Root Beer       270   72.0    0
16                          A&W® Root Beer       440  116.0    0
17                          A&W® Root Beer       880  232.0    0
18                          A&W® Root Beer      1760  464.0    0
19            A&W® Root Beer Float (large)       640  136.0   10
20           A&W® Root Beer Float (medium)       350   77.0    5
21            A&W® Root Beer Float (small)       330   70.0    5
22           A&W® Root Beer Freeze (large)       820  150.0   18
23          A&W® Root Beer Freeze (medium)       480   89.0   10
24           A&W® Root Beer Freeze (small)       370   68.0    8
25                  Blue Raspberry Slushee       270   67.0    0
26                  Blue Raspberry Slushee       370   91.0    0
27                  Blue Raspberry Slushee       570  142.0    0
28                  Blue Raspberry Slushee       740  182.0    0
29             Breaded Onion Rings (Large)       480   62.0   27
30           Breaded Onion Rings (Regular)       350   45.0   16
...                                    ...       ...    ...  ...
4948                    Kids’ French Fries       220   28.0   11
4949                       Kids’ Hamburger       250   25.0   10
4950           Large Caramel Frosty™ Shake       990  195.0   18
4951                           Large Chili       270   31.0    8
4952         Large Chocolate Frosty™ Shake       870  164.0   17
4953                    Large French Fries       500   65.0   24
4954      Large Original Chocolate Frosty™       590   97.0   15
4955        Large Strawberry Frosty™ Shake       780  149.0   15
4956                 Large Vanilla Frosty™       560   93.0   14
4957                   Medium French Fries       410   52.0   20
4958     Medium Original Chocolate Frosty™       410   67.0   10
4959                Medium Vanilla Frosty™       390   65.0   10
4960           Premium Cod Fillet Sandwich       480   51.0   23
4961           Small Caramel Frosty™ Shake       650  121.0   14
4962                           Small Chili       180   20.0    5
4963         Small Chocolate Frosty™ Shake       580  104.0    0
4964                    Small French Fries       310   40.0   15
4965      Small Original Chocolate Frosty™       290   48.0    7
4966        Small Strawberry Frosty™ Shake       540   97.0   12
4967                 Small Vanilla Frosty™       280   46.0    7
4968                     Son of Baconator®       670   41.0   37
4969           Sour Cream and Chive Potato       320   63.0    3
4970            Spicy Chicken Caesar Salad       780   40.0   51
4971  Spicy Chicken Caesar Salad Half-Size       440   28.0   27
4972                 Spicy Chicken Go Wrap       330   30.0   16
4973                Spicy Chicken Sandwich       510   55.0   20
4974                Ultimate Chicken Grill       370   43.0    7
4975                    Value French Fries       220   28.0   11
4976                    Value French Fries       220   28.0   11
4977            Vanilla Frosty Waffle Cone       290   53.0    6

[4977 rows x 4 columns]

Now that our two dataframes have the same index, we can concanate them into one dataframe along the column axis:

# Joining

There are several ways to join two or more data frames. Here's an image to illustrate each possibility:

![](Joins.png)

## Joining practice

Load **foods.csv** into a dataframe.

In [46]:
foods=pd.read_csv('foods.csv')

In [47]:
foods.isnull().sum()

id                 0
name               0
calories           0
carbs            117
fat                0
restaurant_id      0
category_id        1
dtype: int64

In [48]:
foods.head()

   id                 name  calories  carbs  fat  restaurant_id  category_id
0   1  A&W® Diet Root Beer         0    0.0    0              1          1.0
1   2  A&W® Diet Root Beer         0    0.0    0              1          1.0
2   3  A&W® Diet Root Beer         0    0.0    0              1          1.0
3   4  A&W® Diet Root Beer         0    0.0    0              1          1.0
4   5  A&W® Diet Root Beer         0    0.0    0              1          1.0

In [50]:
foods.loc[foods['category_id'].isnull(), :]

        id          name  calories  carbs  fat  restaurant_id  category_id
4061  4062  Qkidz Cookie       190   26.0    9             37          NaN

You'll notice it's the same as the one we concatenated above, with a couple of extra columns: restaurant_id and category_id. These columns correspond to the `id` columns in **categories.csv** and **restaurants.csv**

Load **categories.csv** and **restaurants.csv** into dataframes.

In [101]:

categories = pd.read_csv('categories.csv')
categories.head()

   id      name
0   1    Drinks
1   2    Shakes
2   3     Sides
3   4  Desserts
4   5   Entrees

In [102]:
restaurants = pd.read_csv('restaurants.csv')
restaurants.head()

   id                                   name
0   1                        A&W Restaurants
1   2                             Applebee's
2   3                                 Arby's
3   4                  Atlanta Bread Company
4   5  Bojangle's Famous Chicken 'n Biscuits

Using pandas [merge](http://pandas.pydata.org/pandas-docs/stable/merging.html) method, combine **restaurants** with **foods** along the column axis.

In [103]:
df=pd.merge(foods,restaurants,left_on='restaurant_id',right_on='id')

#save as dataframe
#rename
df.rename(columns={'id_x':'id','name_x':'food','name_y':'restaurant'})
#drop the same column
df.rename(columns={'id_x':'id','name_x':'food','name_y':'restaurant'},inplace=True)
df.drop('id_y',axis=1,inplace=True)

Now combine **categories** with **foods**, keep in mind that _one of the foods does not belong to a category_.

In [127]:
df.head()

,id,food,calories,carbs,fat,restaurant_id,category_id,restaurant,name
0,1,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks
1,2,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks
2,3,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks
3,4,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks
4,5,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks

In [128]:
categories.head()

   category_id      name
0            1    Drinks
1            2    Shakes
2            3     Sides
3            4  Desserts
4            5   Entrees

In [129]:
categories.rename(columns={'id':'category_id'},inplace=True)
categories.head()

   category_id      name
0            1    Drinks
1            2    Shakes
2            3     Sides
3            4  Desserts
4            5   Entrees

In [130]:

df=pd.merge(df,categories,left_on='category_id',right_on='category_id')
#new_df=pd.merge(df,categories,on='category_id')

In [131]:
df

,id,food,calories,carbs,fat,restaurant_id,category_id,restaurant,name_x,name_y
0,1,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
1,2,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
2,3,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
3,4,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
4,5,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
5,6,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
6,13,A&W® Root Beer,160,43.0,0,1,1,A&W Restaurants,Drinks,Drinks
7,14,A&W® Root Beer,220,58.0,0,1,1,A&W Restaurants,Drinks,Drinks
8,15,A&W® Root Beer,270,72.0,0,1,1,A&W Restaurants,Drinks,Drinks
9,16,A&W® Root Beer,440,116.0,0,1,1,A&W Restaurants,Drinks,Drinks
10,17,A&W® Root Beer,880,232.0,0,1,1,A&W Restaurants,Drinks,Drinks
11,18,A&W® Root Beer,1760,464.0,0,1,1,A&W Restaurants,Drinks,Drinks
12,25,Blue Raspberry Slushee,270,67.0,0,1,1,A&W Restaurants,Drinks,Drinks
13,26,Blue Raspberry Slushee,370,91.0,0,1,1,A&W Restaurants,Drinks,Drinks
14,27,Blue Raspberry Slushee,570,142.0,0,1,1,A&W Restaurants,Drinks,Drinks
15,28,Blue Raspberry Slushee,740,182.0,0,1,1,A&W Restaurants,Drinks,Drinks
16,37,Cherry Limeade,190,51.0,0,1,1,A&W Restaurants,Drinks,Drinks
17,38,Cherry Limeade,300,79.0,0,1,1,A&W Restaurants,Drinks,Drinks
18,39,Cherry Limeade,340,90.0,0,1,1,A&W Restaurants,Drinks,Drinks
19,40,Cherry Limeade,530,138.0,0,1,1,A&W Restaurants,Drinks,Drinks
20,41,Cherry Slushee,330,83.0,0,1,1,A&W Restaurants,Drinks,Drinks
21,42,Cherry Slushee,450,112.0,0,1,1,A&W Restaurants,Drinks,Drinks
22,43,Cherry Slushee,570,141.0,0,1,1,A&W Restaurants,Drinks,Drinks
23,44,Cherry Slushee,900,224.0,0,1,1,A&W Restaurants,Drinks,Drinks
24,69,Lemon Slushee,330,82.0,0,1,1,A&W Restaurants,Drinks,Drinks
25,70,Lemon Slushee,440,110.0,0,1,1,A&W Restaurants,Drinks,Drinks
26,71,Lemon Slushee,560,139.0,0,1,1,A&W Restaurants,Drinks,Drinks
27,72,Lemon Slushee,890,221.0,0,1,1,A&W Restaurants,Drinks,Drinks
28,73,Lime Slushee,280,69.0,0,1,1,A&W Restaurants,Drinks,Drinks
29,74,Lime Slushee,380,94.0,0,1,1,A&W Restaurants,Drinks,Drinks
...,...,...,...,...,...,...,...,...,...,...
4946,1215,Chicken Fajitas – w/o Tortillas and Condiments,360,24.0,10,12,28,Chili's,Fajitas,Fajitas
4947,1249,Fajita Trio – w/o Tortillas and Condiments,530,30.0,20,12,28,Chili's,Fajitas,Fajitas
4948,1362,Crispy Taco Shell,60,9.0,2,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4949,1363,Crispy Taco Shell,60,9.0,2,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4950,1366,Flour Tortilla (burrito),290,44.0,9,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4951,1367,Flour Tortilla (taco),90,13.0,2,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4952,1368,Flour Tortilla (taco),90,13.0,2,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4953,1385,Soft Corn Tortilla,60,13.0,0,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4954,1386,Soft Corn Tortilla,60,13.0,0,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4955,1481,California Grille – V (Combo),305,32.0,13,15,30,Corner Bakery Cafe,Paninis,Paninis
4956,1482,California Grille – V (Whole),610,64.0,26,15,30,Corner Bakery Cafe,Paninis,Paninis
4957,1511,Chicken Pomodori (Combo),370,35.0,14,15,30,Corner Bakery Cafe,Paninis,Paninis
4958,1512,Chicken Pomodori (Whole),740,70.0,28,15,30,Corner Bakery Cafe,Paninis,Paninis
4959,1527,Corned Beef Reuben (Combo),380,39.0,18,15,30,Corner Bakery Cafe,Paninis,Paninis
4960,1528,Corned Beef Reuben (Whole),760,78.0,37,15,30,Corner Bakery Cafe,Paninis,Paninis
4961,1529,Corner Club (Combo),365,36.0,15,15,30,Corner Bakery Cafe,Paninis,Paninis
4962,1530,Corner Club (Whole),730,71.0,31,15,30,Corner Bakery Cafe,Paninis,Paninis
4963,1564,Green Chile & Chicken (Combo),370,36.0,13,15,30,Corner Bakery Cafe,Paninis,Paninis
4964,1565,Green Chile & Chicken (Whole),740,72.0,27,15,30,Corner Bakery Cafe,Paninis,Paninis
4965,1568,Grilled Ham & Swiss (Combo),340,35.0,11,15,30,Corner Bakery Cafe,Paninis,Paninis
4966,1569,Grilled Ham & Swiss (Whole),680,70.0,22,15,30,Corner Bakery Cafe,Paninis,Paninis
4967,3210,Chicken McNuggets®,190,12.0,12,30,31,McDonald's,Nuggets,Nuggets
4968,3211,Chicken McNuggets®,280,18.0,18,30,31,McDonald's,Nuggets,Nuggets
4969,3212,Chicken McNuggets®,470,30.0,30,30,31,McDonald's,Nuggets,Nuggets
4970,3756,Chive & Onion,70,2.0,6,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4971,3757,Chive & Onion,130,4.0,11,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4972,3913,Plain,100,1.0,10,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4973,3914,Plain,180,2.0,18,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4974,3917,Reduced Fat Hazelnut,80,3.0,6,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4975,3918,Reduced Fat Hazelnut,140,6.0,11,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads

# Review
---

What are the differences between joining and concatenating?

When would we use one or the other?

In [132]:
#same length: concat
#diff length: joining

In [133]:
foods.head()

   id                 name  calories  carbs  fat  restaurant_id  category_id
0   1  A&W® Diet Root Beer         0    0.0    0              1          1.0
1   2  A&W® Diet Root Beer         0    0.0    0              1          1.0
2   3  A&W® Diet Root Beer         0    0.0    0              1          1.0
3   4  A&W® Diet Root Beer         0    0.0    0              1          1.0
4   5  A&W® Diet Root Beer         0    0.0    0              1          1.0

In [134]:

categories

    category_id                  name
0             1                Drinks
1             2                Shakes
2             3                 Sides
3             4              Desserts
4             5               Entrees
5             6          French Fries
6             7               Burgers
7             8               Chicken
8             9               Seafood
9            10            Appetizers
10           11                Salads
11           12            Sandwiches
12           13                  Ribs
13           14                 Soups
14           15           Kid's Meals
15           16                 Wraps
16           17             Breakfast
17           18                Breads
18           19                Pizzas
19           20           Wing Sauces
20           21                 Wings
21           22       Breakfast Tacos
22           23  Breakfast Sandwiches
23           24              Burritos
24           25                Coffee
25           26                 Tacos
26           27          Mexican Food
27           28               Fajitas
28           29             Tortillas
29           30               Paninis
30           31               Nuggets
31           32  Cream Cheese Spreads

In [135]:
df

,id,food,calories,carbs,fat,restaurant_id,category_id,restaurant,name_x,name_y
0,1,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
1,2,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
2,3,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
3,4,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
4,5,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
5,6,A&W® Diet Root Beer,0,0.0,0,1,1,A&W Restaurants,Drinks,Drinks
6,13,A&W® Root Beer,160,43.0,0,1,1,A&W Restaurants,Drinks,Drinks
7,14,A&W® Root Beer,220,58.0,0,1,1,A&W Restaurants,Drinks,Drinks
8,15,A&W® Root Beer,270,72.0,0,1,1,A&W Restaurants,Drinks,Drinks
9,16,A&W® Root Beer,440,116.0,0,1,1,A&W Restaurants,Drinks,Drinks
10,17,A&W® Root Beer,880,232.0,0,1,1,A&W Restaurants,Drinks,Drinks
11,18,A&W® Root Beer,1760,464.0,0,1,1,A&W Restaurants,Drinks,Drinks
12,25,Blue Raspberry Slushee,270,67.0,0,1,1,A&W Restaurants,Drinks,Drinks
13,26,Blue Raspberry Slushee,370,91.0,0,1,1,A&W Restaurants,Drinks,Drinks
14,27,Blue Raspberry Slushee,570,142.0,0,1,1,A&W Restaurants,Drinks,Drinks
15,28,Blue Raspberry Slushee,740,182.0,0,1,1,A&W Restaurants,Drinks,Drinks
16,37,Cherry Limeade,190,51.0,0,1,1,A&W Restaurants,Drinks,Drinks
17,38,Cherry Limeade,300,79.0,0,1,1,A&W Restaurants,Drinks,Drinks
18,39,Cherry Limeade,340,90.0,0,1,1,A&W Restaurants,Drinks,Drinks
19,40,Cherry Limeade,530,138.0,0,1,1,A&W Restaurants,Drinks,Drinks
20,41,Cherry Slushee,330,83.0,0,1,1,A&W Restaurants,Drinks,Drinks
21,42,Cherry Slushee,450,112.0,0,1,1,A&W Restaurants,Drinks,Drinks
22,43,Cherry Slushee,570,141.0,0,1,1,A&W Restaurants,Drinks,Drinks
23,44,Cherry Slushee,900,224.0,0,1,1,A&W Restaurants,Drinks,Drinks
24,69,Lemon Slushee,330,82.0,0,1,1,A&W Restaurants,Drinks,Drinks
25,70,Lemon Slushee,440,110.0,0,1,1,A&W Restaurants,Drinks,Drinks
26,71,Lemon Slushee,560,139.0,0,1,1,A&W Restaurants,Drinks,Drinks
27,72,Lemon Slushee,890,221.0,0,1,1,A&W Restaurants,Drinks,Drinks
28,73,Lime Slushee,280,69.0,0,1,1,A&W Restaurants,Drinks,Drinks
29,74,Lime Slushee,380,94.0,0,1,1,A&W Restaurants,Drinks,Drinks
...,...,...,...,...,...,...,...,...,...,...
4946,1215,Chicken Fajitas – w/o Tortillas and Condiments,360,24.0,10,12,28,Chili's,Fajitas,Fajitas
4947,1249,Fajita Trio – w/o Tortillas and Condiments,530,30.0,20,12,28,Chili's,Fajitas,Fajitas
4948,1362,Crispy Taco Shell,60,9.0,2,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4949,1363,Crispy Taco Shell,60,9.0,2,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4950,1366,Flour Tortilla (burrito),290,44.0,9,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4951,1367,Flour Tortilla (taco),90,13.0,2,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4952,1368,Flour Tortilla (taco),90,13.0,2,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4953,1385,Soft Corn Tortilla,60,13.0,0,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4954,1386,Soft Corn Tortilla,60,13.0,0,13,29,Chipotle Mexican Grill,Tortillas,Tortillas
4955,1481,California Grille – V (Combo),305,32.0,13,15,30,Corner Bakery Cafe,Paninis,Paninis
4956,1482,California Grille – V (Whole),610,64.0,26,15,30,Corner Bakery Cafe,Paninis,Paninis
4957,1511,Chicken Pomodori (Combo),370,35.0,14,15,30,Corner Bakery Cafe,Paninis,Paninis
4958,1512,Chicken Pomodori (Whole),740,70.0,28,15,30,Corner Bakery Cafe,Paninis,Paninis
4959,1527,Corned Beef Reuben (Combo),380,39.0,18,15,30,Corner Bakery Cafe,Paninis,Paninis
4960,1528,Corned Beef Reuben (Whole),760,78.0,37,15,30,Corner Bakery Cafe,Paninis,Paninis
4961,1529,Corner Club (Combo),365,36.0,15,15,30,Corner Bakery Cafe,Paninis,Paninis
4962,1530,Corner Club (Whole),730,71.0,31,15,30,Corner Bakery Cafe,Paninis,Paninis
4963,1564,Green Chile & Chicken (Combo),370,36.0,13,15,30,Corner Bakery Cafe,Paninis,Paninis
4964,1565,Green Chile & Chicken (Whole),740,72.0,27,15,30,Corner Bakery Cafe,Paninis,Paninis
4965,1568,Grilled Ham & Swiss (Combo),340,35.0,11,15,30,Corner Bakery Cafe,Paninis,Paninis
4966,1569,Grilled Ham & Swiss (Whole),680,70.0,22,15,30,Corner Bakery Cafe,Paninis,Paninis
4967,3210,Chicken McNuggets®,190,12.0,12,30,31,McDonald's,Nuggets,Nuggets
4968,3211,Chicken McNuggets®,280,18.0,18,30,31,McDonald's,Nuggets,Nuggets
4969,3212,Chicken McNuggets®,470,30.0,30,30,31,McDonald's,Nuggets,Nuggets
4970,3756,Chive & Onion,70,2.0,6,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4971,3757,Chive & Onion,130,4.0,11,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4972,3913,Plain,100,1.0,10,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4973,3914,Plain,180,2.0,18,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4974,3917,Reduced Fat Hazelnut,80,3.0,6,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads
4975,3918,Reduced Fat Hazelnut,140,6.0,11,35,32,Panera Bread,Cream Cheese Spreads,Cream Cheese Spreads

In [120]:
df.loc[df['category'].str.contains("Kid"), :].sort_values('calories', ascending=False)

AttributeError: 'Series' object has no attribute 'int'

In [114]:
df.sort_values('calories',ascending=False)

,id,food,calories,carbs,fat,restaurant_id,category_id,restaurant
574,575,20 piece & 10 biscuit box serves 9-11),8820,545.0,540,5,5.0,Bojangle's Famous Chicken 'n Biscuits
564,565,12 piece & 6 biscuit box (serves 5-7),5300,327.0,324,5,5.0,Bojangle's Famous Chicken 'n Biscuits
1535,1536,Country Large Oblong – VG (whole),4220,862.0,16,15,18.0,Corner Bakery Cafe
579,580,8 piece & 4 biscuit box (serves 3-5),3534,218.0,216,5,5.0,Bojangle's Famous Chicken 'n Biscuits
3080,3081,The Big Hook Up,2750,220.0,168,28,9.0,Joe's Crab Shack
1537,1538,Country Small Oblong – VG (whole),2600,532.0,8,15,18.0,Corner Bakery Cafe
1523,1524,Cinnamon Raisin – V (whole),2540,389.0,87,15,18.0,Corner Bakery Cafe
726,727,Ribs & More Ribs,2380,88.0,158,6,5.0,Buffalo Wild Wings
126,127,Appetizer Sampler,2375,169.0,162,2,10.0,Applebee's
1318,1319,Shiner Bock® BBQ Ribs,2310,168.0,123,12,13.0,Chili's
1322,1323,Southern Smokehouse Burger w/ Ancho Chile BBQ ...,2290,163.0,139,12,7.0,Chili's
565,566,12 piece Supremes box (serves 3-5),2230,228.0,92,5,5.0,Bojangle's Famous Chicken 'n Biscuits
1271,1272,Jalapeno Smokehouse Burger w/ Ranch with fries,2210,136.0,144,12,7.0,Chili's
1286,1287,Original Ribs,2170,137.0,123,12,13.0,Chili's
1333,1334,Texas Cheese Fries w/ Chili & Ranch,2120,117.0,144,12,10.0,Chili's
1184,1185,Big Mouth® Bites w/ Ranch with fries,2120,163.0,133,12,7.0,Chili's
3021,3022,East Coast Platter,2110,143.0,144,28,9.0,Joe's Crab Shack
4226,4227,Nacho Ordinary Chili Nachos w/Chicken,2090,133.0,131,38,10.0,Red Robin Gourmet Burgers
1581,1582,Harvest – VG (whole),2080,401.0,15,15,18.0,Corner Bakery Cafe
3007,3008,Crab Nachos,2000,130.0,145,28,10.0,Joe's Crab Shack
3071,3072,Skillet Paella,1990,196.0,84,28,5.0,Joe's Crab Shack
1279,1280,Memphis Dry Rub Ribs,1990,137.0,111,12,13.0,Chili's
2251,2252,Large Fiesta Nachos with Beef,1989,205.0,100,19,10.0,FATZ
3026,3027,Fisherman’s Platter,1970,137.0,129,28,9.0,Joe's Crab Shack
4225,4226,Nacho Ordinary Chili Nachos,1963,132.0,129,38,10.0,Red Robin Gourmet Burgers
1334,1335,Texas Cheese Fries w/ Ranch,1960,109.0,136,12,10.0,Chili's
724,725,Ribs & Boneless Wings,1960,88.0,126,6,5.0,Buffalo Wild Wings
2252,2253,Large Fiesta Nachos with Chicken,1955,190.0,97,19,10.0,FATZ
295,296,New England Fish & Chips,1930,121.0,138,2,9.0,Applebee's
4276,4277,Triple S Riblet & Classic Creamy Mac n Cheese,1921,121.0,117,38,5.0,Red Robin Gourmet Burgers
...,...,...,...,...,...,...,...,...
2461,2462,Fresh Brewed Iced Tea Unsweetened,2,0.0,0,22,1.0,Golden Chick
2939,2940,Iced Tea,2,0.0,0,27,1.0,Jimmy Johns
596,597,Coffee (16oz),0,0.0,0,5,1.0,Bojangle's Famous Chicken 'n Biscuits
1591,1592,Iced Coffee – Black,0,0.0,0,15,25.0,Corner Bakery Cafe
5,6,A&W® Diet Root Beer,0,0.0,0,1,1.0,A&W Restaurants
1590,1591,Iced Coffee – Black,0,0.0,0,15,25.0,Corner Bakery Cafe
1433,1434,Unsweet Tea – Large,0,0.0,0,14,1.0,Church's
1434,1435,Unsweet Tea – Medium,0,0.0,0,14,1.0,Church's
1435,1436,Unsweet Tea – Small,0,0.0,0,14,1.0,Church's
4,5,A&W® Diet Root Beer,0,0.0,0,1,1.0,A&W Restaurants
3,4,A&W® Diet Root Beer,0,0.0,0,1,1.0,A&W Restaurants
2,3,A&W® Diet Root Beer,0,0.0,0,1,1.0,A&W Restaurants
1532,1533,Country Bread Boule – Bowl Option (bowl),0,0.0,0,15,14.0,Corner Bakery Cafe
597,598,Coffee (22oz),0,0.0,0,5,1.0,Bojangle's Famous Chicken 'n Biscuits
3742,3743,Brewed Tea- Black,0,0.0,0,35,1.0,Panera Bread
1883,1884,Coffee,0,0.0,0,17,25.0,Denny's
3226,3227,Coffee,0,0.0,0,30,25.0,McDonald's
3225,3226,Coffee,0,0.0,0,30,25.0,McDonald's
3741,3742,Brewed Tea- Acai,0,0.0,0,35,1.0,Panera Bread
3740,3741,Brewed Tea – Black,0,0.0,0,35,1.0,Panera Bread
3739,3740,Brewed Tea – Acai,0,0.0,0,35,1.0,Panera Bread
4312,4313,Coffee,0,0.0,0,39,1.0,Romano's Macaroni Grill
1,2,A&W® Diet Root Beer,0,0.0,0,1,1.0,A&W Restaurants
631,632,"Unsweetened Iced Tea (16oz, with ice)",0,0.0,0,5,1.0,Bojangle's Famous Chicken 'n Biscuits
632,633,"Unsweetened Iced Tea (22oz, with ice)",0,0.0,0,5,1.0,Bojangle's Famous Chicken 'n Biscuits
633,634,"Unsweetened Iced Tea (32oz, with ice)",0,0.0,0,5,1.0,Bojangle's Famous Chicken 'n Biscuits
4395,4396,San Pellegrino® Sparkling Mineral Water,0,0.0,0,39,1.0,Romano's Macaroni Grill
2740,2741,Herbal Tea,0,2.0,0,24,1.0,IHOP
1149,1150,Iced Tea – Unsweetened,0,0.0,0,11,1.0,Chick-fil-A
0,1,A&W® Diet Root Beer,0,0.0,0,1,1.0,A&W Restaurants

In [140]:
group_restaurant=df.groupby('restaurant').mean()['calories']

In [141]:
group_cate=df.groupby('category_id').mean()['calories']

In [142]:
group_cate

category_id
1.0      246.852000
2.0      597.865497
3.0      243.734082
4.0      480.691517
5.0      724.778626
6.0      460.461538
7.0      755.415888
8.0      449.903743
9.0      786.090000
10.0     807.920000
11.0     462.668555
12.0     608.883197
13.0    1499.000000
14.0     286.684211
15.0     302.967647
16.0     582.218750
17.0     554.472637
18.0     464.716981
19.0     632.916667
20.0      62.823529
21.0      79.285714
22.0     492.571429
23.0     389.846154
24.0     557.936170
25.0     213.794872
26.0     287.795918
27.0     573.339286
28.0     426.666667
29.0     101.428571
30.0     532.500000
31.0     313.333333
32.0     116.666667
Name: calories, dtype: float64